### ISSUE TITLE
1. Architecture : alternative model train software for mqtt

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#21]
At 1. Architecture it says that besides Rocrail another model train can use software, the question is which one is that?

And can you later link the displays to the train track so that they automatically change when the train has left or do you have to adjust it all yourself?

Greetings

**Comment by chrisweather** [comment]
Any software that can send MQTT messages can send content to the displays. I just tested it with Rocrail and Node-Red.

Yes, Rocrail can update the displays when the train leaves the station. This requires more configuration in Rocrail. There are several topics about this in the German Rocrail forum.
