### ISSUE TITLE
Help with making NS logo for display, I can't do it, get weird characters

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#22]
Hi,

The display now works, but I now encounter a new problem and that is making logos for the display, I've been working on it all day and almost all night, but I can't make a nice NS logo , I get those weird characters on the screen, I also don't know what format logos you can use.

So far I've made the logo in monochrome bitmap format, but it won't for the time being.

Which programs do you use to make the logos, can you explain in which format I should make the logo and do you also have to upload the logo or is only the code sufficient? and should the logo be transparent or with a black background?

I hope you can help me with this.

Greetings

**Comment by ksw2404** [comment]
![logo-ns-wit-e1576400966181](https://user-images.githubusercontent.com/109766221/188252989-15af8431-dfcb-4db4-9d78-28fc30aa0573.png)
![e02810aa4e7c30aae3c34f76459b7707](https://user-images.githubusercontent.com/109766221/188252995-8b65a4d4-44b3-4308-b998-ad678902820f.jpg)
![ns1](https://user-images.githubusercontent.com/109766221/188253012-3cae163b-0210-4d6a-a792-611876003140.png)

**Comment by chrisweather** [comment]
The logo should have the size that fits to the display, typically 10 pixel high and up to 20 wide.
I use Gimp to Export it to XBM format.

**Comment by chrisweather** [comment]
Congratulations that you finally got your network settings sorted!

**Comment by ksw2404** [comment]
Hi, it worked, on to the next problem

Greetings
![DTXN9345](https://user-images.githubusercontent.com/109766221/188274174-40ea6674-e84e-4310-a0f4-d9baba33925e.JPG)

**Comment by chrisweather** [comment]
Looks good. Would be great if you could share the picture and the xbm file. I would add it to the next release then.

**Comment by chrisweather** [comment]
If you want me to add the logo to the next release please send the bitmap and xbm file.

**Comment by ksw2404** [comment]
Hi,

Hereby the ns logo

Greetings
[NS.zip](https://github.com/chrisweather/RocMQTTdisplay/files/9625307/NS.zip)

**Comment by chrisweather** [comment]
Thanks! Will add it to 1.08
