### ISSUE TITLE
Create new display button in rocrail

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#23]
Hi,

I am expanding the display buttons in rocrail for extra messages, but that is not going well, display button 4 will not appear, what have I forgotten or what am I doing wrong, see the printscreen, will it see what I mean.

Let me know what's going wrong?

Greetings
![Schermopname (1377)](https://user-images.githubusercontent.com/109766221/188274430-ae62c479-87f4-4fc3-a20a-ea5f0b4bda3f.png)

**Comment by chrisweather** [comment]
We now leave the focus of my project. A better source for help around Rocrail is the Rocrail documentation and the forum.
You used a different button type.
