### ISSUE TITLE
How do you connect a 2, 3 and 4 display that are separately on each platform?

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#24]
Hi,

Now that display 1 is almost ready, I want to start on display 2, 3 and 4, I am building a large station with 4 platforms with 1 display each, the question is how do I build it? I know that every display gets a different controller, but my question is how do you build that from Rocrail how do you know which button to which display? or do you have to put something in the code somewhere in the wemos so that every display knows which one it is, this is what is not quite get it yet. Each platform gets its own display with its own messages?

Please give me a little explanation how best to handle this

Greetings

**Comment by chrisweather** [comment]
You can connect up to eight displays to one controller. If you  want to connect 2 or more you need a multiplexer. There is s wiring example in the wiki.
The messages you send from rocrail can be addressed to specific displays. D01 means the message will be sent only to display 1.
See the example messages in the wiki.

**Comment by ksw2404** [comment]
Hi,

I've seen the wiki example of the wiring, some parts are complicated, I'm mainly concerned with the red and blue wires, they must first be connected with each display and from display 1 a double wiring towards the multiplexer and the wemos D1, which will be soldered, you can no longer do with the jumpers, which I find very vulnerable by the way.

Another question you have not made room on your display for the "via" places or is that mainly due to lack of space? On which screen did you make the display? in real 1:1 I mean, DB has so many types, by the way saw a new screen via google, it looked nice, but I think it is unsuitable for your display and any display

Greetings

**Comment by ksw2404** [comment]
![2289_unit-design-deutsche-bahn-zim-zuginfominitor-002](https://user-images.githubusercontent.com/109766221/188456323-6ed8019e-0806-41c7-bdbd-e6e6937804d5.jpg)

**Comment by chrisweather** [comment]
Every display will be connected with 4 wires. VCC(+), Gnd(-), two data wires.
The multiplexer has connectors for    the data wires of eight displays.
For testing you can use a breadboard and don't need soldering.

The 128x32 displays are very large already compared to all other H0 components. So the only option is to reduce the font size to get more text onto the display.

**Comment by ksw2404** [comment]
Hi,

You recently said that you could connect 8 displays per controller, that is not so difficult to understand, but how do you connect a 2nd controller and especially towards Rocrail, do you have to make a separate plan for each controller or can you use codes for the 2nd controller? or do you have to connect the controllers one by one to the PC or laptop? for the station I need 4 or 5 displays and 5 for the bus station and maybe a few more at other stations and bus stops

So in total I need almost 16 displays, so 2 controllers and 2 multiplexers.

How can I best do this from 1 rocrail page or do I have to make a separate plan for the buses?

Greetings
![RocMQTTDisplay_Architecture](https://user-images.githubusercontent.com/109766221/188686444-0cb191b9-9ad7-46bf-9710-19608fc1e2bf.jpg)
