### ISSUE TITLE
Organize template according to your own idea

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#25]
Hi,

Now that the demo display is ready, I would like to compile 1 template with my own layout, how can you change this without getting completely confused. eg the train number is now under the time, can it also be placed in the position of the running text?

The layout I want =

top left : the time - top center : train number, right top : train company logo.

Bottom stays the same

is this possible and if so which numbers do i need to adjust to get it that way?

**Comment by ksw2404** [comment]
Hi, I managed to make my own Dutch template, with some German accents, so I left the platform number, which is officially not on the Dutch screen and on the Dutch screen it always says via .... information eg Amsterdam via Arnhem etc.

What I do wonder is, you enter the departure time, but do you have to create a new button for each departure time that departs from platform 1 for example? eg 09.00 The Hague and 10.00 Amsterdam, both platform 1 or do you have to set them later so that they automatically switch to the next departure text?

still wondering how this can be solved?

Greetings

**Comment by ksw2404** [comment]
![NS scherm](https://user-images.githubusercontent.com/109766221/188397271-0eb38753-6fe8-4c6f-a29e-252b701d7922.jpg)

**Comment by chrisweather** [comment]
Looks good.
Rocrail sends the message in the text field to the display.
There are several mechanisms in rocrail to write data to a textfield. Actions, Scripts, ...
Some people in the Rocrail forum started to use data from the train schedule. 
I'm not a rocrail expert and cannot help with that.

**Comment by ksw2404** [comment]
Hi,

Do you have a direct link to that forum section, I can see if there is something possible. But if you do it manually do you have to create a new button for each time?

Greetings
