### ISSUE TITLE
Please help connecting the multiplexer, stuck on the red and blue wiring, please help

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#26]
Hi,

I was busy today connecting several displays with a multiplexer in between, only I run into the wiring, one then only the blue and the red wire according to the wiki, I can't figure out how these run?

How is the wiring of Wemos D1 --->> Multiplexer --->> 2 displays, the only wiring that still needs to be connected are the VCC and GND, but the wiki image is not clear.

Can you give a clear explanation how to connect the red and blue wires, I don't use a board, that white thing, so please explain how the wires are connected, both wemos d1, multiplexer and the 2 displays have GND and VCC, you can't put the pin wire in all 3, so how can you?

Greetings

**Comment by chrisweather** [comment]
The wiring picture in the Wiki shows more details now. Every component (controller, multiplexer and all displays) need to connect to GND (-) and VCC (+). A breadboard helps to get the initial wiring set up and test it. When everything works as expected connections can be made permanent e.g. by soldering.

**Comment by ksw2404** [comment]
Hi, I initially managed to get 2 displays working on his white board, until the TCA9548A I2C caught fire, how this was possible is a mystery to me, it's true that I'm not a soldering star and the TCA9548A I2C are only for sale with the separate plug points, do you happen to know where you can get them ready-made? I would have done it slightly different than your picture, but it worked, in the other post I mentioned that if everything worked then it needs to be soldered, but the question is how do you put all the blue and red wires together, on the white board is that's no problem, you would almost think of a distribution plate that is also used in model railways, otherwise I wouldn't know, do you have a suggestion in which way the board setup can be replaced, so all +/- wiring?

Greetings
