### ISSUE TITLE
The displays are ready to use, a few more questions about Multiplexer and Enclosure

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#27]
Hi,

I tested 4 displays on the white board, it went great, then I connected the purple wire (GND) and the red wire (5v) to the busch distribution board and that also worked, so I'm done with this area, only there have yet to come out about the 2 multiplexers, I need more than 8 displays, do you know how to do this together with the rocrail, I understand you need a 2 controller and multiplexer, but how do you combine this with rocrail or should you make a plan in rocrail for the 2nd display set of 8? By the way, do you have a link for the 3d drawing for the housing for the display, find 2 types of a T pole with a display on the left and right and a single pole on the left and right, do you actually use a double sided display on a platform or a single sided ?

Greetings

**Comment by chrisweather** [comment]
For more than 8 displays you need a second controller and multiplexer. Each controller must have a unique name. The default name I use is RocMQTTdisplayC01. You can use any name unless they are different for each controller.
In the configuration each display gets an ID. Default is D01, D02, ...
You can set a unique ID for each display. If you want some displays to always show the same content you can assign the same name to them. E.g. two displays have the ID D03. When you send a MQTT message from Rocrail to D03 both displays will show the content. Even when they are connected to different controllers.

I don't have an enclosure link or file for printing. If you find a good one let me know.

**Comment by ksw2404** [comment]
Hi, ok I already have a 2nd controller and multiplexer, but do you just count the unique code or do you start again at 1 with the 2nd controller and how does that work with rocrail, do you have to make a new plan or can you do the same use plan and proceed with multiple display numbers. So you have to name the 2nd controller RocMQTTdisplayC02 and you have to connect the controller and multiplexer 1 and 2 at the same time to use it via rocrail.

That's because I use 4 displays for the station / platform, 4 displays for the bus station and then 2 train displays on the next station and 1 on the other bus station at that station building and possibly some on the way, so I need at least 10 displays .

and later it will be the intention that the displays will run automatically when the train departs and that the following message will appear, but I have not yet figured out how this works, but will come.

Greetings

**Comment by chrisweather** [comment]
I have added some more explanation for the data flow with two or more controllers to the Wiki
https://github.com/chrisweather/RocMQTTdisplay/wiki/7.-Format-and-Examples

**Comment by ksw2404** [comment]
Hi,

part of the picture is clear, eg you have to give each controller a separate browser page, but now it specifically says to use wifi, does that mean you have to run the controllers over wifi? now everything runs via the fixed cable to the pc and via ethernet. Can you also connect by connecting both controllers to the PC, then connect both to the mosquitto and thus to rocrail or do you have to turn off ethernet and run on wifi and also let the controllers run via wifi instead of the cables?

Assume that the same ip address should be noted in browser page 1 and 2?

And what about uloading to the controller, can that be done from the same documents folder where the display files are located or does a new folder have to be created for the controller 2 with the data files in it?

Greetings

**Comment by chrisweather** [comment]
You just need a USB connection to the PC for loading the initial software and data folder to the controller. After that the controller connects via WiFi to your network. The USB cable is just the power connection then. You can also use any other 5V USB charger. 
The browser is on required to change any configuration settings on the controller. This happens via WiFi. Just type http://yourControllerName to get into the configuration of the controller.

**Comment by chrisweather** [comment]
Enclosure §D printing files for a basic case can be found here: https://github.com/chrisweather/RocMQTTdisplay/tree/main/case
