### ISSUE TITLE
Is it possible to change background color? from black to white

### ISSUE THREAD

**Issue by ksw2404** [chrisweather/RocMQTTdisplay#28]
Hi,

is it possible to change the background color of the display from black to white? So that the text turns black?

**Comment by ksw2404** [comment]
![screenshot](https://user-images.githubusercontent.com/109766221/191450987-05f7284a-6602-4eea-aa81-36f53dbaf5d9.jpg)

**Comment by ksw2404** [comment]
like the example

**Comment by ksw2404** [comment]
![277589714_1776733505864253_2653987178288419471_n](https://user-images.githubusercontent.com/109766221/191455377-55da0b20-6ca2-45ad-8530-018ffab5c0b6.jpg)

**Comment by chrisweather** [comment]
Will be possible in the next version. It just needs some more testing.

**Comment by chrisweather** [comment]
Added invert function to v1.08
